services:
  challenge-api:
    image: redteamsubnet61/flowprint-challenge:0.0.0
    build:
      context: ./src/flp_challenge/challenge
    platform: linux/amd64
    privileged: true
    restart: unless-stopped
    environment:
      TERM: ${TERM:-xterm}
      TZ: ${TZ:-UTC}
      FLP_API_PORT: ${FLP_API_PORT:-10001}
      FLP_API_DATA_DIR: ${FLP_API_DATA_DIR:-/var/lib/flowprint-challenge}
    env_file:
      - path: .env
    volumes:
      - "./volumes/configs/flowprint-challenge:${FLP_API_CONFIGS_DIR:-/etc/flowprint-challenge}"
      - "./volumes/storage/flowprint-challenge/logs:${FLP_API_LOGS_DIR:-/var/log/flowprint-challenge}"
      - "./volumes/storage/flowprint-challenge/data:${FLP_API_DATA_DIR:-/var/lib/flowprint-challenge}"
    ports:
      - "${FLP_API_PORT:-10001}:${FLP_API_PORT:-10001}"
    tty: true
