import math
from typing import Any

MIN_VALUE_COUNT = 20
RARE_VALUE = "__rare__"


def _to_float(value: Any) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return 0.0


def _bucket_ttl(value):
    ttl = _to_float(value)
    if ttl <= 0:
        return "unknown"
    if ttl <= 64:
        return "64"
    if ttl <= 128:
        return "128"
    return "255"


def _normalize(value):
    if value is None:
        return "missing"
    text = str(value).strip()
    if not text or text.lower() in {"nan", "none", "null"}:
        return "missing"
    try:
        number = float(text)
    except ValueError:
        return text
    if number == int(number):
        return str(int(number))
    return text


def extract_value(row, feature):
    if feature == "ip_ttl_bucket":
        return _bucket_ttl(row.get("ip_ttl"))
    return _normalize(row.get(feature))


def detect_os(features: dict[str, Any], model: dict[str, Any]) -> str:
    """Return the most likely device OS for a flow.

    This reference detector consumes the count-table JSON generated by
    train.py. Miners can replace this implementation, but the function
    signature is the v2 contract.
    """
    classes = model.get("classes", [])
    classes_total = model.get("class_total", {})
    counts = model.get("counts", {})
    feature_names = model.get("features") or list(counts)
    default_class = model.get("default_class")
    if not classes or not counts:
        return default_class or ""
    scores = {}
    for os_name in classes:
        total = classes_total.get(os_name, 0)
        score = 0.0
        for feature in feature_names:
            value = extract_value(features, feature)
            table = counts.get(feature, {})
            class_counts = table.get(value) or table.get(RARE_VALUE) or {}
            seen = class_counts.get(os_name, 0)
            score += math.log((seen + 1) / (total + len(classes)))
        scores[os_name] = score
    return max(scores, key=scores.get)


__all__ = ["detect_os"]
